# Generated by Django 3.2.22 on 2023-10-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=40)),
                ('info', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('img', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
